/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.janelas;

import static controle.Controle.getControle;
import controle.ItemFilaDownload;
import controle.ItemFilaUpload;
import exceptions.ConexaoEncerrada;
import exceptions.RespostaTimeoutException;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import static java.lang.Thread.sleep;
import javax.naming.SizeLimitExceededException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import modelo.ArquivoExtendido;
import modelo.Helpers;
import modelo.InterfaceHook;
import modelo.cliente.Usuario;
import modelo.exceptions.ArquivoInexistenteException;
import modelo.exceptions.OfflineException;
import modelo.exceptions.SemUsuarioException;

/**
 *
 * @author giovani
 */
public class JanelaConta extends javax.swing.JFrame {

    /**
     * Creates new form JanelaImagemPerfil
     */
    public JanelaConta(Usuario usr) {
        initComponents();
        
        usuarioNaoEditado = usr;
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                getControle().getControleJanelas().fecharTelaConta();
            }  
        });
        
        if (usr.getSHA256ImagemPerfil()!= null) {
            ItemFilaDownload ifila = new ItemFilaDownload(usr.getSHA256ImagemPerfil(), new InterfaceHook<ArquivoExtendido>(){
                @Override
                public void run(ArquivoExtendido obj) {
                    if (obj != null) {
                        setAvatarDownloadConcluido(obj);
                    }
                }
            });

            getControle().getControleConexoes().novoDownload(ifila);
        }

        else {
            jLabel11.setIcon(Helpers.IMG_ICON_PADRAO);
        }
        
        jLabel3.setText(usr.getUsuario());
        jTextField1.setText(usr.getApelidoUsuario());
        jPasswordField1.setText("");
        jLabel9.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gerenciando conta");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Seu usuário:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel3.setText("<não carregado>");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 167, -1));

        jLabel4.setText("Seu apelido:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jTextField1.setText("<não carregado>");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 160, -1));

        jLabel5.setText("Nova senha?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 160, -1));

        jButton1.setText("Destruir conta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 240, -1));

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 240, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("X");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 20, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Selecionar imagem");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/user-icon 128.png"))); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 180));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 110, 10));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 10, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        arquivoImagem = null;
        
        if (avatarAnterior != null) {
            try {
                jLabel11.setIcon(Helpers.redmImagemLabel(avatarAnterior.getArquivo(), jLabel11));
            } catch (IOException ex) {}
        }
        
        else {
            jLabel11.setIcon(Helpers.IMG_ICON_PADRAO);
        }

        jLabel9.setVisible(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        jLabel9.setForeground(Color.BLUE);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        jLabel9.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        JFileChooser jfc = new JFileChooser();
        jfc.setFileFilter(ArquivoExtendido.EXTENSOES_IMAGENS);
        jfc.setMultiSelectionEnabled(false);
        
        if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                arquivoImagem = new ArquivoExtendido(jfc.getSelectedFile());
                
                jLabel11.setIcon(Helpers.redmImagemLabel(arquivoImagem.getArquivo(), jLabel11));
                jLabel9.setVisible(true);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Não foi possível carregar o arquivo.");
            } catch (SizeLimitExceededException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        jLabel10.setForeground(Color.BLUE);
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        jLabel10.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel10MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        idArquivoRecebido = null;
        respostaEnvioRecebido = false;
        
        if (arquivoImagem != null) {      
            ItemFilaUpload item = new ItemFilaUpload(new InterfaceHook<String>() {
                @Override
                public void run(String obj) {
                    JanelaConta.this.respostaEnvioArquivoRecebido(obj);
                }
            }, arquivoImagem);
            
            getControle().getControleConexoes().novoUpload(item);
            
            while (!respostaEnvioRecebido) {
                try {
                    sleep(10);
                } catch (InterruptedException ex) {}
            }
            
            //dialog.dispose();
            
            if (idArquivoRecebido == null) {
                JOptionPane.showMessageDialog(this, "Imagem não alterada devido uma falha.!");
            }
            
            else {
                try {
                    getControle().getControleConexoes().alterarImagemPerfil(usuarioNaoEditado, idArquivoRecebido);
                    
                    usuarioNaoEditado.setSHA256ImagemPerfil(idArquivoRecebido);
                    avatarAnterior = arquivoImagem;

                    JOptionPane.showMessageDialog(this, "Imagem alterada com sucesso!");
                } catch (ConexaoEncerrada | RespostaTimeoutException | SemUsuarioException | ArquivoInexistenteException | OfflineException ex) {
                    JOptionPane.showMessageDialog(this, "Imagem não alterada devido uma falha!");
                }
            }
        }
        
        if (!jTextField1.getText().equals(usuarioNaoEditado.getApelidoUsuario())) {
            try {
                getControle().getControleConexoes().alterarApelido(usuarioNaoEditado, jTextField1.getText());
                
                usuarioNaoEditado.setApelidoUsuario(jTextField1.getText());
            
                JOptionPane.showMessageDialog(this, "Apelido alterado com sucesso!");
            } catch (ConexaoEncerrada | SemUsuarioException | OfflineException | RespostaTimeoutException ex) {
                JOptionPane.showMessageDialog(this, "Apelido não alterado devido uma falha!");
            }
        }
        
        if (jPasswordField1.getPassword().length != 0) {
            try {
                getControle().getControleConexoes().alterarSenha(usuarioNaoEditado, new String(jPasswordField1.getPassword()));
                
                JOptionPane.showMessageDialog(this, "Senha alterada com sucesso!");
            } catch (ConexaoEncerrada | SemUsuarioException | OfflineException | RespostaTimeoutException ex) {
                JOptionPane.showMessageDialog(this, "Senha não alterada devido uma falha!");
            }
        }
        
        jPasswordField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void respostaEnvioArquivoRecebido(String resposta) {
        idArquivoRecebido = resposta;
        respostaEnvioRecebido = true;
    }
    
    private void setAvatarDownloadConcluido(ArquivoExtendido arq) {
        try {
            if (arquivoImagem == null) {
                jLabel11.setIcon(Helpers.redmImagemLabel(arq.getArquivo(), jLabel11));
            }
            
            avatarAnterior = arq;
        } catch (IOException ex) {}
    }
    
    private ArquivoExtendido arquivoImagem = null;
    private volatile String idArquivoRecebido = null;
    private volatile boolean respostaEnvioRecebido = false;
    private ArquivoExtendido avatarAnterior = null;
    private Usuario usuarioNaoEditado;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
