/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo.frames;

import static controle.Controle.getControle;
import controle.ItemFilaDownload;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import modelo.ArquivoExtendido;
import modelo.Helpers;
import modelo.InterfaceHook;
import modelo.cliente.Usuario;

/**
 *
 * @author Giovani
 */
public class UsuarioLista extends javax.swing.JPanel {

    /**
     * Creates new form UsuarioLista
     */
    public UsuarioLista(Usuario usr) {
        initComponents();
        
        jLabel2.setText(usr.getApelidoUsuario());
        

        if (usr.getSHA256ImagemPerfil() != null) {
            getControle().getControleConexoes().novoDownload(new ItemFilaDownload(usr.getSHA256ImagemPerfil(), new InterfaceHook<ArquivoExtendido>() {
                @Override
                public void run(ArquivoExtendido obj) {
                    if (obj != null) {
                        try {
                            jLabel1.setIcon(Helpers.redmImagemLabel(obj.getArquivo(), 49, 49));
                        } catch (IOException ex) {}
                    }
                    
                    else {
                        try {
                            BufferedImage img = ImageIO.read(UsuarioLista.class.getResource("/visao/imagens/user-icon 72.png"));
                            
                            jLabel2.setIcon(new ImageIcon(img.getScaledInstance(49, 49, Image.SCALE_FAST)));
                        } catch (IOException ex) {
                            getControle().getControleLogger().logarErro("Um componente de imagem já incluso no software não foi encontrado: user-icon 128.png", true);
                        }
                    }
                }
            }));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
